# Generated by Django 5.0.9 on 2024-10-31 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_testlist_profile_photo_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestList',
        ),
    ]
