# Generated by Django 5.0.9 on 2024-10-31 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_testlist'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testlist',
            table='TESTLIST',
        ),
    ]
