# Generated by Django 5.0.9 on 2024-11-01 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_testlist_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestList',
        ),
    ]
